# Generated by Django 3.1.3 on 2022-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220330_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='useremail',
            field=models.EmailField(default='', max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='이메일'),
        ),
    ]
