# Generated by Django 3.1.3 on 2022-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20220401_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name='이미지'),
        ),
    ]
