# Generated by Django 3.1.3 on 2022-04-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220330_0222'),
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='email',
            field=models.ForeignKey(blank=True, db_column='account_useremail', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.account', verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지'),
        ),
    ]
