# Generated by Django 3.1.3 on 2022-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20220401_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=128, verbose_name='이메일'),
        ),
    ]
