# Generated by Django 3.1.3 on 2022-04-02 11:07

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220402_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='email',
            field=models.CharField(default='', max_length=128, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=pybo.models.file_name, verbose_name='이미지'),
        ),
    ]
