# Generated by Django 3.2.5 on 2022-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20220515_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
